/*
 * Copyright (c) 2024 Nordic Semiconductor ASA
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#if defined(CONFIG_BT_CTLR_NRF_GRTC)
#define HAL_CNTR_GRTC_CC_IDX_TICKER 10
#define HAL_CNTR_GRTC_EVENT_COMPARE_TICKER \
	_CONCAT(NRF_GRTC_EVENT_COMPARE_, HAL_CNTR_GRTC_CC_IDX_TICKER)
#define HAL_CNTR_GRTC_INTENSET_COMPARE_TICKER_Msk \
	_CONCAT(_CONCAT(GRTC_INTENSET1_COMPARE, HAL_CNTR_GRTC_CC_IDX_TICKER), _Msk)
#define HAL_CNTR_GRTC_CC_IDX_RADIO  11
#define HAL_CNTR_GRTC_EVENT_COMPARE_RADIO \
	_CONCAT(NRF_GRTC_EVENT_COMPARE_, HAL_CNTR_GRTC_CC_IDX_RADIO)

#if defined(CONFIG_BT_CTLR_PREEMPT_TIMEOUT_CNTR)
#define HAL_CNTR_GRTC_CC_IDX_PREEMPT 12
#define HAL_CNTR_GRTC_EVENT_COMPARE_PREEMPT \
	_CONCAT(NRF_GRTC_EVENT_COMPARE_, HAL_CNTR_GRTC_CC_IDX_PREEMPT)
#define HAL_CNTR_GRTC_INTENSET_COMPARE_PREEMPT_Msk \
	_CONCAT(_CONCAT(GRTC_INTENSET1_COMPARE, HAL_CNTR_GRTC_CC_IDX_PREEMPT), _Msk)
#define HAL_CNTR_GRTC_INTENCLR_COMPARE_PREEMPT_Msk \
	_CONCAT(_CONCAT(GRTC_INTENCLR1_COMPARE, HAL_CNTR_GRTC_CC_IDX_PREEMPT), _Msk)
#endif /* CONFIG_BT_CTLR_PREEMPT_TIMEOUT_CNTR */

#else /* !CONFIG_BT_CTLR_NRF_GRTC */

#if defined(CONFIG_BT_CTLR_PREEMPT_TIMEOUT_CNTR)
/* NRF_RTC compare channel for preempt timeout.
 * CC0 = ticker, CC2 = radio timer start, CC1 is free.
 */
#define HAL_CNTR_RTC_CC_IDX_PREEMPT 1
#endif /* CONFIG_BT_CTLR_PREEMPT_TIMEOUT_CNTR */

#endif /* CONFIG_BT_CTLR_NRF_GRTC */
