CONFIG_BT=y
CONFIG_BT_OBSERVER=y
CONFIG_BT_ISO_SYNC_RECEIVER=y
CONFIG_LOG=y
CONFIG_BT_DEVICE_NAME="Test ISO Receive"

# For multiple broadcast sources, increase these values accordingly:
# CONFIG_BT_ISO_MAX_CHAN >= 2 * CONFIG_ISO_BROADCAST_SOURCE_COUNT
# CONFIG_BT_PER_ADV_SYNC_MAX >= CONFIG_ISO_BROADCAST_SOURCE_COUNT
CONFIG_BT_ISO_MAX_CHAN=2
